[package]
name = "noughts_and_crosses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.4.0"
rand = "0.8.5"

[[bench]]
name = "solver"
harness = false
